### PR TITLE
fixes and more stable installation on already installed nagios systems

### PR DESCRIPTION
**Pull request by pablodav**
* Remove nagios3 from debian packages if installed
* Added more compatible version with check_mk for other roles created to automate nagios at CoffeeITWorks.

### CODE REVIEW

**Comment by ogenstad** [comment]
There seems to be a lot of commits for what is just an addition of 6 lines?

```
+- name: Remove Nagios3 for Ubuntu
 +  apt: pkg={{ item }} state=absent
 +  with_items:
 +   - nagios3
 +   - nagios3-core
 +   - check-mk-livestatus
```

I'm guessing the reason behind this is that you've run into issues when you're trying to install Nagios 4 on systems which already has a Nagios 3 installation?

Also see that the tests are failing, that looks like it's due to some changes on the Travis side and different behaviour in recent versions of Ansible. I'll take a look at those.

**Comment by pablodav** [comment]
Those changes have long time in our fork, and I just wanted to collaborate to your main project creating the pull request. 

Yes we had nagios3 installed in some servers and that task helps in migrating from old setup to new with ansible. (It helps and works)

I had problems with travis, so all the roles I have I migrated to circleci, it works better for me. 

Example file: https://github.com/CoffeeITWorks/ansible_burp2_server/blob/master/circle.yml 

I have also many good nagios roles that could help you, all of them using your role to install nagios so all compatibles with it. 

https://github.com/CoffeeITWorks

Still need to get some time to add tests, but we are using it in production with 2000 service very stable. 

Ones of the most interesting roles could be these: 

https://github.com/CoffeeITWorks/ansible_nagios4_server_snmptrap
https://github.com/CoffeeITWorks/ansible_nagios4_server_plugins
https://github.com/CoffeeITWorks/ansible_nagios4_server_config

There is also others optional: 
https://github.com/CoffeeITWorks/ansible_nagios4_server_thruk
https://github.com/CoffeeITWorks/ansible_nagios4_server_pnp4nagios

Hope all those could be useful too.

**Comment by ogenstad** [comment]
I've fixed the Travis tests in another commit. Regarding the removal of packages. Does `check-mk-livestatus` actually get in the way if it's installed?

**Comment by pablodav** [comment]
check-mk-livestatus is too old to be used with nagios4 in debian/ubuntu repos. 

I'm actually using it only as livestatus for thruk interface, so this role builds and installs it at this task: 

https://github.com/CoffeeITWorks/ansible_nagios4_server_thruk/blob/master/tasks/build-check-mk-livestatus.yml 

Do you think it is required a separate role to build and install so anyone can use it without thruk?

**Comment by ogenstad** [comment]
My main issue is the uninstallation of other packages which might or might not be useful. Does the current check-mk-livestatus get in the way of anything? The current package in the Debian/Ubuntu repo might be too old, but people can use other repos or if the creator makes a package that version might be compatible, in that scenario this would uninstall something that might actually be in use.

**Comment by pablodav** [comment]
Your point of view is true and I agree, so I have added it as an optional task disabled by default . 

In defaults/main.yml: 

```yaml
# This option will be used if you want to uninstall debian packages for nagios and check-mk-livestatus
ansible-role-nagios-remove-packages: no
```

And with conditional option in the task.

**Comment by ogenstad** [comment]
This looks better and thank you for your contribution!

**Pull request merged**
